services:
  runner:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TOKEN=<Github PAT token>
      - ORG=OpenTix
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 256M
